### ISSUE TITLE
Pandas is omitted

### ISSUE THREAD

**Issue by brijrajsingh** [SumanMore/TaskGPT#5]
https://github.com/SumanMore/TaskGPT/blob/0a9b795643138478cd29301f1a7eb1ea06de6731/requirements.txt#L1

Shouldn't pandas be part of this requirements.txt. You can cross check using the pip freeze command to make sure all dependencies are part of the requirements.txt

**Comment by SumanMore** [comment]
when we install streamlit (in requirements.txt), pandas also get automatically configured
